---
services:
  vault:
    image: hashicorp/vault
    container_name: vault
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=myroot
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:1234
    cap_add:
      - IPC_LOCK
    ports:
      - "4321:1234"
